[book]
authors = ["Zhifei Yang"]
language = "en"
multilingual = false
src = "src"
title = "ETH Course Guide"

[output.html]
git-repository-edit-url-template = "https://github.com/Xivid/ETH-Course-Guide/edit/master/{path}"
disqus-shortname = "ethz-xyz"
