# This is a basic workflow to help you get started with Actions

name: Publish mdbook

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Deploy book
      run: |
        wget https://github.com/Xivid/mdBook/releases/download/selfv1/mdbook
        chmod +x mdbook
        echo Generate book
        cd ETH-Course-Guide
        git checkout master
        ../mdbook build
        cd ETH-Course-Guide
        git checkout gh-pages || git checkout -b gh-pages
        git pull origin gh-pages --rebase
        echo ls@gh-pages
        ls -al
        echo Copy book sources
        cp -R book/* .
        git clean -fx book
        git add .
        COMMIT_MESSAGE="Update mdbook `date '+%Y-%m-%d %H:%M:%S'`"
        git commit -a -m "${COMMIT_MESSAGE}"
        git push -u origin gh-pages
        git checkout master
